//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerulean.LangPacks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangPack() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cerulean.LangPacks.LangPack", typeof(LangPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate!.
        /// </summary>
        internal static string ABOUT_BUTTON_DONATE {
            get {
                return ResourceManager.GetString("ABOUT_BUTTON_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me.
        /// </summary>
        internal static string ABOUT_BUTTON_FOLLOW_MAINTAINER {
            get {
                return ResourceManager.GetString("ABOUT_BUTTON_FOLLOW_MAINTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post about Cerulean.
        /// </summary>
        internal static string ABOUT_BUTTON_POST_CERULEAN {
            get {
                return ResourceManager.GetString("ABOUT_BUTTON_POST_CERULEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, and thanks for using my client! It&apos;s currently in the beta stage, which means a fair chunk of stuff
        ///is incomplete or unimplemented. I would appreciate it if you contacted me about potential
        ///new features I could add or things I could change.
        ///
        ///This client is meant to replace Bluesky completely. As the official app and wesbite use the public 
        ///API, everything possible with the app is also possible in a third-party client. I want to add all Bluesky&apos;s 
        ///features (and more) to this client.
        ///
        ///Contact:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABOUT_LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Cerulean.
        /// </summary>
        internal static string ABOUT_WINTITLE {
            get {
                return ResourceManager.GetString("ABOUT_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean.
        /// </summary>
        internal static string CBOX_WINTITLE {
            get {
                return ResourceManager.GetString("CBOX_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Feed.
        /// </summary>
        internal static string FEEDSEL_BUTTON_SELECT_FEED {
            get {
                return ResourceManager.GetString("FEEDSEL_BUTTON_SELECT_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string FEEDSEL_BUTTON_TIMELINE {
            get {
                return ResourceManager.GetString("FEEDSEL_BUTTON_TIMELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a feed to view..
        /// </summary>
        internal static string FEEDSEL_CBOX_SELECTFEED {
            get {
                return ResourceManager.GetString("FEEDSEL_CBOX_SELECTFEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may choose a feed to view, or choose &quot;Timeline&quot; to view your timeline..
        /// </summary>
        internal static string FEEDSEL_LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("FEEDSEL_LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FEEDSEL_LIST_DESCRIPTION {
            get {
                return ResourceManager.GetString("FEEDSEL_LIST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        internal static string FEEDSEL_LIST_FEED {
            get {
                return ResourceManager.GetString("FEEDSEL_LIST_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feed name.
        /// </summary>
        internal static string FEEDSEL_LIST_NO_NAME {
            get {
                return ResourceManager.GetString("FEEDSEL_LIST_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Selector.
        /// </summary>
        internal static string FEEDSEL_WINTITLE {
            get {
                return ResourceManager.GetString("FEEDSEL_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string GLOBAL_BUTTON_APPLY {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GLOBAL_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GLOBAL_BUTTON_OK {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check server status.
        /// </summary>
        internal static string GLOBAL_BUTTON_PING_SERVER {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_PING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string GLOBAL_BUTTON_RESET {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all fields.
        /// </summary>
        internal static string GLOBAL_INFOLABEL_EMPTY_FIELDS {
            get {
                return ResourceManager.GetString("GLOBAL_INFOLABEL_EMPTY_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image viewer.
        /// </summary>
        internal static string IMGVIEWER_WINTITLE {
            get {
                return ResourceManager.GetString("IMGVIEWER_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDS Host.
        /// </summary>
        internal static string LOGIN_BUTTON_CHANGEPDS {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_CHANGEPDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string LOGIN_BUTTON_FORGOTPASS {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_FORGOTPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LOGIN_BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string LOGIN_CHECKBOX_REMEMBER_CREDENTIALS {
            get {
                return ResourceManager.GetString("LOGIN_CHECKBOX_REMEMBER_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluesky handle.
        /// </summary>
        internal static string LOGIN_LABEL_HANDLE {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LOGIN_LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account?.
        /// </summary>
        internal static string LOGIN_LINKLABEL_NEWACCOUNT {
            get {
                return ResourceManager.GetString("LOGIN_LINKLABEL_NEWACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to PDS host.
        /// </summary>
        internal static string LOGIN_LOCALMSG_CONNECTING_TO_PDS {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_CONNECTING_TO_PDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean is connecting to Bluesky. If authentication fails, check PDS host and login details..
        /// </summary>
        internal static string LOGIN_LOCALMSG_CONNECTING_TO_PDS_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_CONNECTING_TO_PDS_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Cerulean..
        /// </summary>
        internal static string LOGIN_LOCALMSG_DEFAULT {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in with your Bluesky account. App password is recommended..
        /// </summary>
        internal static string LOGIN_LOCALMSG_DEFAULT_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_DEFAULT_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that both the handle and password fields are filled..
        /// </summary>
        internal static string LOGIN_LOCALMSG_EMPTY_FIELD_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_EMPTY_FIELD_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid debug code.
        /// </summary>
        internal static string LOGIN_LOCALMSG_INVALID_DEBUGCODE {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_INVALID_DEBUGCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug code that you have entered is invalid..
        /// </summary>
        internal static string LOGIN_LOCALMSG_INVALID_DEBUGCODE_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_INVALID_DEBUGCODE_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean Login.
        /// </summary>
        internal static string LOGIN_WINTITLE {
            get {
                return ResourceManager.GetString("LOGIN_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string MAIN_BUTTON_POST {
            get {
                return ResourceManager.GetString("MAIN_BUTTON_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Messaging.
        /// </summary>
        internal static string MAIN_CBOX_ABSENT_DM {
            get {
                return ResourceManager.GetString("MAIN_CBOX_ABSENT_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s happening?.
        /// </summary>
        internal static string MAIN_QTBOX_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MAIN_QTBOX_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bluesky.
        /// </summary>
        internal static string MAIN_SEARCHBOX_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MAIN_SEARCHBOX_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load results.
        /// </summary>
        internal static string MAIN_SEARCHLIST_FAILED {
            get {
                return ResourceManager.GetString("MAIN_SEARCHLIST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles found.
        /// </summary>
        internal static string MAIN_SEARCHLIST_NORESULT {
            get {
                return ResourceManager.GetString("MAIN_SEARCHLIST_NORESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for users....
        /// </summary>
        internal static string MAIN_SEARCHLIST_SEARCHING {
            get {
                return ResourceManager.GetString("MAIN_SEARCHLIST_SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string MAIN_TBUTTON_LOGOUT {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Direct Message.
        /// </summary>
        internal static string MAIN_TBUTTON_NEW_DM {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_NEW_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        internal static string MAIN_TBUTTON_NEW_POST {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_NEW_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MAIN_TBUTTON_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reauthenticate.
        /// </summary>
        internal static string MAIN_TBUTTON_REAUTH {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_REAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Feed.
        /// </summary>
        internal static string MAIN_TBUTTON_SELECT_FEED {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_SELECT_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string MAIN_TLABEL_CONNECTED {
            get {
                return ResourceManager.GetString("MAIN_TLABEL_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string MAIN_TLABEL_DISCONNECTED {
            get {
                return ResourceManager.GetString("MAIN_TLABEL_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG: Offline User.
        /// </summary>
        internal static string MAIN_TLABEL_HANDLE_OFFLINE {
            get {
                return ResourceManager.GetString("MAIN_TLABEL_HANDLE_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /issues/new.
        /// </summary>
        internal static string MAIN_URL_CERULEANGITERRPATH {
            get {
                return ResourceManager.GetString("MAIN_URL_CERULEANGITERRPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/OmegaAOL/cerulean.
        /// </summary>
        internal static string MAIN_URL_CERULEANGITREPO {
            get {
                return ResourceManager.GetString("MAIN_URL_CERULEANGITREPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ceruleanweb.neocities.org/.
        /// </summary>
        internal static string MAIN_URL_CERULEANWEB {
            get {
                return ResourceManager.GetString("MAIN_URL_CERULEANWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean.
        /// </summary>
        internal static string MAIN_WINTITLE {
            get {
                return ResourceManager.GetString("MAIN_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check server status.
        /// </summary>
        internal static string PDS_BUTTON_PING_SERVER {
            get {
                return ResourceManager.GetString("PDS_BUTTON_PING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you are trying to use is invalid. Remember, no slashes or special characters at the end..
        /// </summary>
        internal static string PDS_CBOX_INVALID_CHAR {
            get {
                return ResourceManager.GetString("PDS_CBOX_INVALID_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine software version of PDS server {0}. This is either not a PDS server or incompatible with Cerulean..
        /// </summary>
        internal static string PDS_CBOX_PDS_PING_ERROR {
            get {
                return ResourceManager.GetString("PDS_CBOX_PDS_PING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDS server {0}/ is online. The server is running software version {1}. This should be compatible with Cerulean..
        /// </summary>
        internal static string PDS_CBOX_PDS_PING_RESULT {
            get {
                return ResourceManager.GetString("PDS_CBOX_PDS_PING_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDS host has been reset to {0}..
        /// </summary>
        internal static string PDS_CBOX_URL_RESET {
            get {
                return ResourceManager.GetString("PDS_CBOX_URL_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom PDS host has been saved..
        /// </summary>
        internal static string PDS_CBOX_URL_SAVED {
            get {
                return ResourceManager.GetString("PDS_CBOX_URL_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Bluesky PDS hosts your data and federates with the
        ///wider AT Protocol to create a social network.
        ///
        ///You may host your own PDS. To make Cerulean use your
        ///PDS instead of the default (https://bsky.social), change it here.
        ///
        ///There is no official support for alternative microblogging services..
        /// </summary>
        internal static string PDS_LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("PDS_LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDS Host.
        /// </summary>
        internal static string PDS_WINTITLE {
            get {
                return ResourceManager.GetString("PDS_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string RESETPW_BUTTON_SEND_EMAIL {
            get {
                return ResourceManager.GetString("RESETPW_BUTTON_SEND_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        internal static string RESETPW_INFOLABEL_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("RESETPW_INFOLABEL_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong password recommended.
        /// </summary>
        internal static string RESETPW_INFOLABEL_STRONG_PASSWORD {
            get {
                return ResourceManager.GetString("RESETPW_INFOLABEL_STRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account email.
        /// </summary>
        internal static string RESETPW_LABEL_EMAIL {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string RESETPW_LABEL_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset code.
        /// </summary>
        internal static string RESETPW_LABEL_RESET_CODE {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_RESET_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Enter the e-mail address you used to register with Bluesky. You will 
        ///recieve a password reset e-mail..
        /// </summary>
        internal static string RESETPW_LABEL_STEP1 {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_STEP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Enter a new password of your choosing, along with the password
        ///reset code that you received in the mail:.
        /// </summary>
        internal static string RESETPW_LABEL_STEP2 {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_STEP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string RESETPW_WINTITLE {
            get {
                return ResourceManager.GetString("RESETPW_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted post.
        /// </summary>
        internal static string TC_LABEL_DELETED {
            get {
                return ResourceManager.GetString("TC_LABEL_DELETED", resourceCulture);
            }
        }
    }
}
