//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerulean.LangPacks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangPack() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cerulean.LangPacks.LangPack", typeof(LangPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate!.
        /// </summary>
        internal static string ABOUT_BUTTON_DONATE {
            get {
                return ResourceManager.GetString("ABOUT_BUTTON_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me.
        /// </summary>
        internal static string ABOUT_BUTTON_FOLLOW_MAINTAINER {
            get {
                return ResourceManager.GetString("ABOUT_BUTTON_FOLLOW_MAINTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post about Cerulean.
        /// </summary>
        internal static string ABOUT_BUTTON_POST_CERULEAN {
            get {
                return ResourceManager.GetString("ABOUT_BUTTON_POST_CERULEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        internal static string ABOUT_CBOX_FEATUREABSENT_DONATIONS {
            get {
                return ResourceManager.GetString("ABOUT_CBOX_FEATUREABSENT_DONATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        internal static string ABOUT_CBOX_THANKS {
            get {
                return ResourceManager.GetString("ABOUT_CBOX_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, and thanks for using my client! It&apos;s currently in the beta stage, which means a fair chunk of stuff
        ///is incomplete or unimplemented. I would appreciate it if you contacted me about potential
        ///new features I could add or things I could change.
        ///
        ///This client is meant to replace Bluesky completely. As the official app and wesbite use the public 
        ///API, everything possible with the app is also possible in a third-party client. I want to add all Bluesky&apos;s 
        ///features (and more) to this client.
        ///
        ///Contact:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABOUT_LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I use Cerulean, a Bluesky client for Windows 98 - 11. Try it at.
        /// </summary>
        internal static string ABOUT_TXT_PROMO {
            get {
                return ResourceManager.GetString("ABOUT_TXT_PROMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Cerulean.
        /// </summary>
        internal static string ABOUT_WINTITLE {
            get {
                return ResourceManager.GetString("ABOUT_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean.
        /// </summary>
        internal static string CBOX_WINTITLE {
            get {
                return ResourceManager.GetString("CBOX_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account suspended or banned.
        /// </summary>
        internal static string ERR_ACCTAKEDOWN_HEAD {
            get {
                return ResourceManager.GetString("ERR_ACCTAKEDOWN_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has taken down your account temporarily or permanently. If in doubt, contact your PDS administrator..
        /// </summary>
        internal static string ERR_ACCTAKEDOWN_SUB {
            get {
                return ResourceManager.GetString("ERR_ACCTAKEDOWN_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login details.
        /// </summary>
        internal static string ERR_BADCRED_HEAD {
            get {
                return ResourceManager.GetString("ERR_BADCRED_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login credentials you have provided are invalid. If you used your email to log in, use your handle instead..
        /// </summary>
        internal static string ERR_BADCRED_SUB {
            get {
                return ResourceManager.GetString("ERR_BADCRED_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid 2FA code.
        /// </summary>
        internal static string ERR_BADTWOFA_HEAD {
            get {
                return ResourceManager.GetString("ERR_BADTWOFA_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid, or expired, two-factor authentication code. Please log in again with a valid code..
        /// </summary>
        internal static string ERR_BADTWOFA_SUB {
            get {
                return ResourceManager.GetString("ERR_BADTWOFA_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to server.
        /// </summary>
        internal static string ERR_CANTRESOLVEHOST_HEAD {
            get {
                return ResourceManager.GetString("ERR_CANTRESOLVEHOST_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean could not reach the server. Check your internet connection and PDS host settings..
        /// </summary>
        internal static string ERR_CANTRESOLVEHOST_SUB {
            get {
                return ResourceManager.GetString("ERR_CANTRESOLVEHOST_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION: {0}.
        /// </summary>
        internal static string ERR_DESC {
            get {
                return ResourceManager.GetString("ERR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty response from server.
        /// </summary>
        internal static string ERR_NORESPONSE_HEAD {
            get {
                return ResourceManager.GetString("ERR_NORESPONSE_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null, empty, or blank response received from the server..
        /// </summary>
        internal static string ERR_NORESPONSE_SUB {
            get {
                return ResourceManager.GetString("ERR_NORESPONSE_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string ERR_PREFIX {
            get {
                return ResourceManager.GetString("ERR_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate limit exceeded.
        /// </summary>
        internal static string ERR_RATELIMIT_HEAD {
            get {
                return ResourceManager.GetString("ERR_RATELIMIT_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is rate limiting your account. Try again later, or contact Bluesky/your PDS administrator..
        /// </summary>
        internal static string ERR_RATELIMIT_SUB {
            get {
                return ResourceManager.GetString("ERR_RATELIMIT_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error is unhandled by Cerulean (it&apos;s server-side). Report this on GitHub..
        /// </summary>
        internal static string ERR_SERVER_SUB {
            get {
                return ResourceManager.GetString("ERR_SERVER_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error in SkyBridge.
        /// </summary>
        internal static string ERR_SKY_HEAD {
            get {
                return ResourceManager.GetString("ERR_SKY_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from server.
        /// </summary>
        internal static string ERR_SKY_INVALID_HEAD {
            get {
                return ResourceManager.GetString("ERR_SKY_INVALID_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned a response that Cerulean cannot process..
        /// </summary>
        internal static string ERR_SKY_INVALID_SUB {
            get {
                return ResourceManager.GetString("ERR_SKY_INVALID_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyBridge encountered internal problems when attempting to communicate with the server, namely:.
        /// </summary>
        internal static string ERR_SKY_SUB {
            get {
                return ResourceManager.GetString("ERR_SKY_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication required.
        /// </summary>
        internal static string ERR_TWOFA_HEAD {
            get {
                return ResourceManager.GetString("ERR_TWOFA_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an authentication code to log in; if you do not want to, use an app password or disable 2FA..
        /// </summary>
        internal static string ERR_TWOFA_SUB {
            get {
                return ResourceManager.GetString("ERR_TWOFA_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, I use Cerulean, a client for Bluesky. Try it out at https://ceruleanweb.neocities.org/.
        /// </summary>
        internal static string EXTERN_EMAIL_BODY {
            get {
                return ResourceManager.GetString("EXTERN_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this post on Bluesky!.
        /// </summary>
        internal static string EXTERN_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("EXTERN_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Feed.
        /// </summary>
        internal static string FEEDSEL_BUTTON_SELECT_FEED {
            get {
                return ResourceManager.GetString("FEEDSEL_BUTTON_SELECT_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string FEEDSEL_BUTTON_TIMELINE {
            get {
                return ResourceManager.GetString("FEEDSEL_BUTTON_TIMELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a feed to view..
        /// </summary>
        internal static string FEEDSEL_CBOX_SELECTFEED {
            get {
                return ResourceManager.GetString("FEEDSEL_CBOX_SELECTFEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may choose a feed to view, or choose &quot;Timeline&quot; to view your timeline..
        /// </summary>
        internal static string FEEDSEL_LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("FEEDSEL_LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FEEDSEL_LIST_DESCRIPTION {
            get {
                return ResourceManager.GetString("FEEDSEL_LIST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        internal static string FEEDSEL_LIST_FEED {
            get {
                return ResourceManager.GetString("FEEDSEL_LIST_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feed name.
        /// </summary>
        internal static string FEEDSEL_LIST_NO_NAME {
            get {
                return ResourceManager.GetString("FEEDSEL_LIST_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string FEEDSEL_TIMELINE {
            get {
                return ResourceManager.GetString("FEEDSEL_TIMELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Selector.
        /// </summary>
        internal static string FEEDSEL_WINTITLE {
            get {
                return ResourceManager.GetString("FEEDSEL_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string GLOBAL_BUTTON_APPLY {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GLOBAL_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GLOBAL_BUTTON_OK {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check server status.
        /// </summary>
        internal static string GLOBAL_BUTTON_PING_SERVER {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_PING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string GLOBAL_BUTTON_RESET {
            get {
                return ResourceManager.GetString("GLOBAL_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No display name.
        /// </summary>
        internal static string GLOBAL_DISPLAYNAME_EMPTY {
            get {
                return ResourceManager.GetString("GLOBAL_DISPLAYNAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! There was an error in Cerulean. Press OK to continue. .
        /// </summary>
        internal static string GLOBAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all fields.
        /// </summary>
        internal static string GLOBAL_INFOLABEL_EMPTY_FIELDS {
            get {
                return ResourceManager.GetString("GLOBAL_INFOLABEL_EMPTY_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string GLOBAL_UNKNOWN {
            get {
                return ResourceManager.GetString("GLOBAL_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string GLOBAL_YES {
            get {
                return ResourceManager.GetString("GLOBAL_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may add an image to your post:.
        /// </summary>
        internal static string IMAGESEL_LABEL_ADD_PICTURE {
            get {
                return ResourceManager.GetString("IMAGESEL_LABEL_ADD_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a description?.
        /// </summary>
        internal static string IMAGESEL_TEXTBOXHINT_DESC {
            get {
                return ResourceManager.GetString("IMAGESEL_TEXTBOXHINT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an image.
        /// </summary>
        internal static string IMAGESEL_WINTITLE {
            get {
                return ResourceManager.GetString("IMAGESEL_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image viewer.
        /// </summary>
        internal static string IMGVIEWER_WINTITLE {
            get {
                return ResourceManager.GetString("IMGVIEWER_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDS Host.
        /// </summary>
        internal static string LOGIN_BUTTON_CHANGEPDS {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_CHANGEPDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string LOGIN_BUTTON_FORGOTPASS {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_FORGOTPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LOGIN_BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string LOGIN_CHECKBOX_REMEMBER_CREDENTIALS {
            get {
                return ResourceManager.GetString("LOGIN_CHECKBOX_REMEMBER_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluesky handle.
        /// </summary>
        internal static string LOGIN_LABEL_HANDLE {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LOGIN_LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account?.
        /// </summary>
        internal static string LOGIN_LINKLABEL_NEWACCOUNT {
            get {
                return ResourceManager.GetString("LOGIN_LINKLABEL_NEWACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to PDS host.
        /// </summary>
        internal static string LOGIN_LOCALMSG_CONNECTING_TO_PDS {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_CONNECTING_TO_PDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean is connecting to Bluesky. If authentication fails, check PDS host and login details..
        /// </summary>
        internal static string LOGIN_LOCALMSG_CONNECTING_TO_PDS_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_CONNECTING_TO_PDS_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Cerulean..
        /// </summary>
        internal static string LOGIN_LOCALMSG_DEFAULT {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in with your Bluesky account. App password is recommended..
        /// </summary>
        internal static string LOGIN_LOCALMSG_DEFAULT_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_DEFAULT_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that both the handle and password fields are filled..
        /// </summary>
        internal static string LOGIN_LOCALMSG_EMPTY_FIELD_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_EMPTY_FIELD_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid debug code.
        /// </summary>
        internal static string LOGIN_LOCALMSG_INVALID_DEBUGCODE {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_INVALID_DEBUGCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug code that you have entered is invalid. Please refer to the Cerulean website for a list of debug codes..
        /// </summary>
        internal static string LOGIN_LOCALMSG_INVALID_DEBUGCODE_SUB {
            get {
                return ResourceManager.GetString("LOGIN_LOCALMSG_INVALID_DEBUGCODE_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean Login.
        /// </summary>
        internal static string LOGIN_WINTITLE {
            get {
                return ResourceManager.GetString("LOGIN_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string MAIN_BUTTON_POST {
            get {
                return ResourceManager.GetString("MAIN_BUTTON_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Messaging.
        /// </summary>
        internal static string MAIN_CBOX_ABSENT_DM {
            get {
                return ResourceManager.GetString("MAIN_CBOX_ABSENT_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature hasn&apos;t been added to Cerulean yet. Check if it&apos;s available in the latest version.\n\nFeature:.
        /// </summary>
        internal static string MAIN_CBOX_FEATUREABSENT {
            get {
                return ResourceManager.GetString("MAIN_CBOX_FEATUREABSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s happening?.
        /// </summary>
        internal static string MAIN_QTBOX_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MAIN_QTBOX_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bluesky.
        /// </summary>
        internal static string MAIN_SEARCHBOX_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MAIN_SEARCHBOX_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load results.
        /// </summary>
        internal static string MAIN_SEARCHLIST_FAILED {
            get {
                return ResourceManager.GetString("MAIN_SEARCHLIST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles found.
        /// </summary>
        internal static string MAIN_SEARCHLIST_NORESULT {
            get {
                return ResourceManager.GetString("MAIN_SEARCHLIST_NORESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for users....
        /// </summary>
        internal static string MAIN_SEARCHLIST_SEARCHING {
            get {
                return ResourceManager.GetString("MAIN_SEARCHLIST_SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add feed (+).
        /// </summary>
        internal static string MAIN_TAB_NEW {
            get {
                return ResourceManager.GetString("MAIN_TAB_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content.
        /// </summary>
        internal static string MAIN_TABS_NO_CONTENT {
            get {
                return ResourceManager.GetString("MAIN_TABS_NO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string MAIN_TBUTTON_LOGOUT {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Direct Message.
        /// </summary>
        internal static string MAIN_TBUTTON_NEW_DM {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_NEW_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        internal static string MAIN_TBUTTON_NEW_POST {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_NEW_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MAIN_TBUTTON_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reauthenticate.
        /// </summary>
        internal static string MAIN_TBUTTON_REAUTH {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_REAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Feed.
        /// </summary>
        internal static string MAIN_TBUTTON_SELECT_FEED {
            get {
                return ResourceManager.GetString("MAIN_TBUTTON_SELECT_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string MAIN_TLABEL_CONNECTED {
            get {
                return ResourceManager.GetString("MAIN_TLABEL_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string MAIN_TLABEL_DISCONNECTED {
            get {
                return ResourceManager.GetString("MAIN_TLABEL_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG: Offline User.
        /// </summary>
        internal static string MAIN_TLABEL_HANDLE_OFFLINE {
            get {
                return ResourceManager.GetString("MAIN_TLABEL_HANDLE_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean.
        /// </summary>
        internal static string MAIN_WINTITLE {
            get {
                return ResourceManager.GetString("MAIN_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further use of this program assumes that you have read and agree to the Cerulean Terms, found at.
        /// </summary>
        internal static string MSG_FIRSTRUN_TERMS {
            get {
                return ResourceManager.GetString("MSG_FIRSTRUN_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running a &apos;legacy kernel&apos; version of Windows (9x/ME/NT4). This comes with a few caveats:\n\n&quot; +
        ///                &quot;1: Fonts will probably not display properly as Microsoft Sans Serif is not installed by default on your system.\n\n2: The encryption used to save &quot; +
        ///                &quot;your handle and password is the legacy CeruleanCrypt method, and not DPAPI. This is less secure.\n\n3: Generally expect some things to be broken..
        /// </summary>
        internal static string MSG_WIN9XWARNING {
            get {
                return ResourceManager.GetString("MSG_WIN9XWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check server status.
        /// </summary>
        internal static string PDS_BUTTON_PING_SERVER {
            get {
                return ResourceManager.GetString("PDS_BUTTON_PING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you are trying to use is invalid. Remember, no slashes or special characters at the end..
        /// </summary>
        internal static string PDS_CBOX_INVALID_CHAR {
            get {
                return ResourceManager.GetString("PDS_CBOX_INVALID_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine software version of PDS server {0}. This is either not a PDS server or incompatible with Cerulean..
        /// </summary>
        internal static string PDS_CBOX_PDS_PING_ERROR {
            get {
                return ResourceManager.GetString("PDS_CBOX_PDS_PING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDS server {0}/ is online. The server is running software version {1}. This should be compatible with Cerulean..
        /// </summary>
        internal static string PDS_CBOX_PDS_PING_RESULT {
            get {
                return ResourceManager.GetString("PDS_CBOX_PDS_PING_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDS host has been reset to {0}..
        /// </summary>
        internal static string PDS_CBOX_URL_RESET {
            get {
                return ResourceManager.GetString("PDS_CBOX_URL_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom PDS host has been saved..
        /// </summary>
        internal static string PDS_CBOX_URL_SAVED {
            get {
                return ResourceManager.GetString("PDS_CBOX_URL_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Bluesky PDS hosts your data and federates with the
        ///wider AT Protocol to create a social network.
        ///
        ///You may host your own PDS. To make Cerulean use your
        ///PDS instead of the default (https://bsky.social), change it here.
        ///
        ///There is no official support for alternative microblogging services..
        /// </summary>
        internal static string PDS_LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("PDS_LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDS Host.
        /// </summary>
        internal static string PDS_WINTITLE {
            get {
                return ResourceManager.GetString("PDS_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string PROFILE_BUTTON_FOLLOW {
            get {
                return ResourceManager.GetString("PROFILE_BUTTON_FOLLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string PROFILE_BUTTON_UNBLOCK {
            get {
                return ResourceManager.GetString("PROFILE_BUTTON_UNBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string PROFILE_BUTTON_UNFOLLOW {
            get {
                return ResourceManager.GetString("PROFILE_BUTTON_UNFOLLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        internal static string PROFILE_BUTTON_UNMUTE {
            get {
                return ResourceManager.GetString("PROFILE_BUTTON_UNMUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline User.
        /// </summary>
        internal static string PROFILE_LABEL_OFFLINEUSER {
            get {
                return ResourceManager.GetString("PROFILE_LABEL_OFFLINEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Verifier.
        /// </summary>
        internal static string PROFILE_LABEL_VERIFIER {
            get {
                return ResourceManager.GetString("PROFILE_LABEL_VERIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appeal a previously taken moderation action.
        /// </summary>
        internal static string REPORT_APPEAL {
            get {
                return ResourceManager.GetString("REPORT_APPEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed as Report #.
        /// </summary>
        internal static string REPORT_CBOX_FILED {
            get {
                return ResourceManager.GetString("REPORT_CBOX_FILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misleading identity, affiliation, or content.
        /// </summary>
        internal static string REPORT_MISLEADING {
            get {
                return ResourceManager.GetString("REPORT_MISLEADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports not falling under another report category.
        /// </summary>
        internal static string REPORT_OTHER {
            get {
                return ResourceManager.GetString("REPORT_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harassing, explicit, or otherwise unwelcoming behavior.
        /// </summary>
        internal static string REPORT_RUDE {
            get {
                return ResourceManager.GetString("REPORT_RUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwanted or mislabeled sexual content.
        /// </summary>
        internal static string REPORT_SEXUAL {
            get {
                return ResourceManager.GetString("REPORT_SEXUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequent unwanted promotion, replies, mentions.
        /// </summary>
        internal static string REPORT_SPAM {
            get {
                return ResourceManager.GetString("REPORT_SPAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct violation of server rules, laws, terms of service.
        /// </summary>
        internal static string REPORT_VIOLATION {
            get {
                return ResourceManager.GetString("REPORT_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string RESETPW_BUTTON_SEND_EMAIL {
            get {
                return ResourceManager.GetString("RESETPW_BUTTON_SEND_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        internal static string RESETPW_INFOLABEL_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("RESETPW_INFOLABEL_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong password recommended.
        /// </summary>
        internal static string RESETPW_INFOLABEL_STRONG_PASSWORD {
            get {
                return ResourceManager.GetString("RESETPW_INFOLABEL_STRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account email.
        /// </summary>
        internal static string RESETPW_LABEL_EMAIL {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string RESETPW_LABEL_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset code.
        /// </summary>
        internal static string RESETPW_LABEL_RESET_CODE {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_RESET_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Enter the e-mail address you used to register with Bluesky. You will 
        ///recieve a password reset e-mail..
        /// </summary>
        internal static string RESETPW_LABEL_STEP1 {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_STEP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Enter a new password of your choosing, along with the password
        ///reset code that you received in the mail:.
        /// </summary>
        internal static string RESETPW_LABEL_STEP2 {
            get {
                return ResourceManager.GetString("RESETPW_LABEL_STEP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string RESETPW_WINTITLE {
            get {
                return ResourceManager.GetString("RESETPW_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string SETTINGS_BUTTON_CHECK_UPDATES {
            get {
                return ResourceManager.GetString("SETTINGS_BUTTON_CHECK_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature reset to default.
        /// </summary>
        internal static string SETTINGS_LABEL_DS_RESET {
            get {
                return ResourceManager.GetString("SETTINGS_LABEL_DS_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature saved.
        /// </summary>
        internal static string SETTINGS_LABEL_DS_SAVED {
            get {
                return ResourceManager.GetString("SETTINGS_LABEL_DS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running version:.
        /// </summary>
        internal static string SETTINGS_LABEL_VERSION_CURRENT {
            get {
                return ResourceManager.GetString("SETTINGS_LABEL_VERSION_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        internal static string SETTINGS_LABEL_VERSION_LATEST {
            get {
                return ResourceManager.GetString("SETTINGS_LABEL_VERSION_LATEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature.
        /// </summary>
        internal static string SETTINGS_PAGE_DS {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string SETTINGS_PAGE_THEME {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string SETTINGS_PAGE_UPDATES {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean Preferences.
        /// </summary>
        internal static string SETTINGS_WINTITLE {
            get {
                return ResourceManager.GetString("SETTINGS_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted post.
        /// </summary>
        internal static string TC_LABEL_DELETED {
            get {
                return ResourceManager.GetString("TC_LABEL_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levels deep.
        /// </summary>
        internal static string TC_LABEL_DEPTH {
            get {
                return ResourceManager.GetString("TC_LABEL_DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surface level.
        /// </summary>
        internal static string TC_LABEL_DEPTH_0 {
            get {
                return ResourceManager.GetString("TC_LABEL_DEPTH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 level deep.
        /// </summary>
        internal static string TC_LABEL_DEPTH_1 {
            get {
                return ResourceManager.GetString("TC_LABEL_DEPTH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes.
        /// </summary>
        internal static string TC_LABEL_LIKE_PLURAL {
            get {
                return ResourceManager.GetString("TC_LABEL_LIKE_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        internal static string TC_LABEL_LIKE_SINGULAR {
            get {
                return ResourceManager.GetString("TC_LABEL_LIKE_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string TC_LABEL_TIME_DAY {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string TC_LABEL_TIME_HOUR {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string TC_LABEL_TIME_MINUTE {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string TC_LABEL_TIME_MONTH {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string TC_LABEL_TIME_NOW {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string TC_LABEL_TIME_WEEK {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string TC_LABEL_TIME_YEAR {
            get {
                return ResourceManager.GetString("TC_LABEL_TIME_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown time.
        /// </summary>
        internal static string TC_LABEL_UNKNOWN_TIME {
            get {
                return ResourceManager.GetString("TC_LABEL_UNKNOWN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmark.
        /// </summary>
        internal static string TC_LINKLABEL_BOOKMARK {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_BOOKMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand.
        /// </summary>
        internal static string TC_LINKLABEL_EXPAND_GENERIC {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_EXPAND_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand image.
        /// </summary>
        internal static string TC_LINKLABEL_EXPAND_IMAGE {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_EXPAND_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand video.
        /// </summary>
        internal static string TC_LINKLABEL_EXPAND_VIDEO {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_EXPAND_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        internal static string TC_LINKLABEL_QUOTE {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        internal static string TC_LINKLABEL_REPLY {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_REPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repost.
        /// </summary>
        internal static string TC_LINKLABEL_REPOST {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_REPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reposted.
        /// </summary>
        internal static string TC_LINKLABEL_REPOSTED {
            get {
                return ResourceManager.GetString("TC_LINKLABEL_REPOSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post does not have any replies..
        /// </summary>
        internal static string TVIEW_NOPOSTS {
            get {
                return ResourceManager.GetString("TVIEW_NOPOSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post by.
        /// </summary>
        internal static string TVIEW_WINTITLE {
            get {
                return ResourceManager.GetString("TVIEW_WINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading post thread....
        /// </summary>
        internal static string TVIEW_WINTITLE_LOADING {
            get {
                return ResourceManager.GetString("TVIEW_WINTITLE_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 character left.
        /// </summary>
        internal static string TWEET_LABEL_CHARCOUNT_ONECHAR {
            get {
                return ResourceManager.GetString("TWEET_LABEL_CHARCOUNT_ONECHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters left.
        /// </summary>
        internal static string TWEET_LABEL_CHARCOUNT_REMAINING {
            get {
                return ResourceManager.GetString("TWEET_LABEL_CHARCOUNT_REMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoting.
        /// </summary>
        internal static string TWEET_TEXTBOX_QUOTE_PRE {
            get {
                return ResourceManager.GetString("TWEET_TEXTBOX_QUOTE_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string TWEET_WINTITLE_QUOTE_PRE {
            get {
                return ResourceManager.GetString("TWEET_WINTITLE_QUOTE_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to.
        /// </summary>
        internal static string TWEET_WINTITLE_REPLYTO_PRE {
            get {
                return ResourceManager.GetString("TWEET_WINTITLE_REPLYTO_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid two-factor code..
        /// </summary>
        internal static string TWOFA_CBOX_NOCODE {
            get {
                return ResourceManager.GetString("TWOFA_CBOX_NOCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has requested that you provide a two-factor authentication code to log in. Please enter it here:.
        /// </summary>
        internal static string TWOFA_LABEL_CONTENT {
            get {
                return ResourceManager.GetString("TWOFA_LABEL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your 2FA code.
        /// </summary>
        internal static string TWOFA_WINTITLE {
            get {
                return ResourceManager.GetString("TWOFA_WINTITLE", resourceCulture);
            }
        }
    }
}
