//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerulean.LangPacks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cerulean.LangPacks.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did:plc:3eu7dl4zieh66ufh5374dsmw.
        /// </summary>
        internal static string DID_CERULEAN {
            get {
                return ResourceManager.GetString("DID_CERULEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did:plc:lcjzu6ssrwr2ifdvpckvdwew.
        /// </summary>
        internal static string DID_MAINTAINER {
            get {
                return ResourceManager.GetString("DID_MAINTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /issues/new.
        /// </summary>
        internal static string GIT_ERROR_PATH {
            get {
                return ResourceManager.GetString("GIT_ERROR_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ceruleanweb.neocities.org.
        /// </summary>
        internal static string HOMEPAGE {
            get {
                return ResourceManager.GetString("HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bsky.app.
        /// </summary>
        internal static string HOMEPAGE_BLUESKY {
            get {
                return ResourceManager.GetString("HOMEPAGE_BLUESKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bsky.social.
        /// </summary>
        internal static string PDS_BLUESKY {
            get {
                return ResourceManager.GetString("PDS_BLUESKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/OmegaAOL/cerulean.
        /// </summary>
        internal static string REPOSITORY {
            get {
                return ResourceManager.GetString("REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ceruleanweb.neocities.org/legal/terms.
        /// </summary>
        internal static string TERMS {
            get {
                return ResourceManager.GetString("TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bsky.social/about/support/tos.
        /// </summary>
        internal static string TERMS_BLUESKY {
            get {
                return ResourceManager.GetString("TERMS_BLUESKY", resourceCulture);
            }
        }
    }
}
